
language: python
python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "3.2"

sudo: true

before_install:
  - pip install coverage --user
  - pip install nose2

install:
  - sudo python setup.py install

script: nose2

